# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
default_language_version:
  python: python3.8
exclude: 'setup.cfg'
repos:
  - repo: local
    hooks:
      - id: check-unit-tests
        name: Check Unit Tests
        entry: bash -c 'make unit'
        language: system
        types: [python]
        require_serial: true
        fail_fast: true
      - id: run-format
        name: Fix the format of files
        entry: bash -c 'make format'
        language: system
        types: [python]
        require_serial: true
        fail_fast: true
      - id: check-lint
        name: Run pylint for the files
        entry: bash -c 'make lint'
        language: system
        types: [python]
        require_serial: true
        fail_fast: true
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ".*"
        args: [--project=activities/vcc]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use the latest stable version
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8